name: Transform Rime Clinic Dicts to Sougou

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  transform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install rimetool
      run: pip install rimetool

    - name: Process Rime Clinic Dicts
      run: |
        for file in rime_clinic_dicts/cn_dict/*; do
          rimetool -i "$file" -t tosougou
          prefix=$(basename "$file" | cut -d '.' -f 1)
          mv "/home/runner/work/rime_clinic/rime_clinic/rimetool_output/tosougou_output.txt" "/home/runner/work/rime_clinic/rime_clinic/sougou_dicts/cn_dict/$prefix.txt"
        done

    # - name: Save processed files
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: sougou_dicts
    #     path: /home/runner/work/rime_clinic/rime_clinic/sougou_dicts/cn_dict/
    - name: Commit and push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
        commit_message: "Update Sougou dicts"
